const talukData = {
    AndhraPradesh: {
      Anantapur: ["Anantapur", "Dharmavaram", "Hindupur"],
      Chittoor: ["Chittoor", "Madanapalle", "Tirupati"],
      EastGodavari: ["Kakinada", "Rajahmundry", "Amalapuram"],
      Guntur: ["Guntur", "Tenali", "Narasaraopet"],
      Krishna: ["Machilipatnam", "Vijayawada", "Nuzvid"],
      Kurnool: ["Kurnool", "Adoni", "Nandyal"],
      Prakasam: ["Ongole", "Kandukur", "Chirala"],
      Nellore: ["Nellore", "Kavali", "Gudur"],
      Srikakulam: ["Srikakulam", "Palasa", "Tekkali"],
      Visakhapatnam: ["Visakhapatnam", "Vizianagaram", "Anakapalle"],
      Vizianagaram: ["Vizianagaram", "Bobbili", "Parvathipuram"],
      WestGodavari: ["Eluru", "Bhimavaram", "Tanuku"],
      YSRKadapa: ["Kadapa", "Proddatur", "Rajampet"]
    },
    ArunachalPradesh: {
      Tawang: ["Tawang", "Jang", "Lumla"],
      WestKameng: ["Bomdila", "Dirang", "Kalaktang"],
      EastKameng: ["Seppa", "Chayang Tajo", "Bameng"],
      PapumPare: ["Itanagar", "Naharlagun", "Sagalee"],
      LowerSubansiri: ["Ziro", "Yachuli", "Raga"],
      UpperSubansiri: ["Daporijo", "Dumporijo", "Taliha"]
    },
    Assam: {
      Baksa: ["Mussoorie", "Gohpur", "Barama"],
      Barpeta: ["Barpeta", "Sarthebari", "Bajali"],
      Bongaigaon: ["Bongaigaon", "Boitamari", "Bijni"],
      Cachar: ["Silchar", "Lakhipur", "Sachin"],
      Darrang: ["Mangaldai", "Kharupatia", "Dalgaon"],
      Dhemaji: ["Dhemaji", "Silapathar", "Jonai"],
      Dhubri: ["Dhubri", "Gauripur", "Bilasipara"],
      Dibrugarh: ["Dibrugarh", "Tingkhong", "Moran"],
      Goalpara: ["Goalpara", "Lakhipur", "Dudhnoi"],
      Golaghat: ["Golaghat", "Bokakhat", "Sarupathar"],
      Hailakandi: ["Hailakandi", "Lala", "Algapur"],
      Jorhat: ["Jorhat", "Mariani", "Titabor"],
      Kamrup: ["Guwahati", "Chamaria", "Rangia"],
      KamrupMetropolitan: ["Guwahati", "Chamaria", "Rangia"],
      KarbiAnglong: ["Diphu", "Bokajan", "Donkamokam"],
      Karimganj: ["Karimganj", "Badarpur", "Patharkandi"],
      Kokrajhar: ["Kokrajhar", "Kachugaon", "Gossaigaon"],
      Lakhimpur: ["NorthLakhimpur", "Dhakuakhana", "Bihpuria"],
      Morigaon: ["Morigaon", "Lahorighat", "Bhuragaon"],
      Nagaon: ["Nagaon", "Kaliabor", "Raha"],
      Nalbari: ["Nalbari", "Tihu", "Barkhetry"],
      Sivasagar: ["Sivasagar", "Amguri", "Nazira"],
      Sonitpur: ["Tezpur", "BiswanathChariali", "Gohpur"],
      SouthSalmaraMankachar: ["Hatsingimari", "Mankachar", "Sutarkandi"],
      Tinsukia: ["Tinsukia", "Digboi", "Doomdooma"],
      Udalguri: ["Udalguri", "Tangla", "Kalaigaon"]
    },
    Bihar: {
      Araria: ["Araria", "Forbesganj", "Jokihat"],
      Arwal: ["Arwal", "Kaler", "Kurtha"],
      Aurangabad: ["Aurangabad", "Daudnagar", "Nabinagar"],
      Banka: ["Banka", "Amarpur", "Belhar"],
      Begusarai: ["Begusarai", "Balia", "Khudabandpur"],
      Bhagalpur: ["Bhagalpur", "Kahalgaon", "Nathnagar"],
      Bhojpur: ["Ara", "Jagdishpur", "Piro"],
      Buxar: ["Buxar", "Chausa", "Nawanagar"],
      Darbhanga: ["Darbhanga", "Benipur", "Alinagar"],
      EastChamparan: ["Motihari", "Chakia", "Dhaka"],
      Gaya: ["Gaya", "BodhGaya", "Sherghati"],
      Gopalganj: ["Gopalganj", "Hathua", "Sidhwaliya"],
      Jamui: ["Jamui", "Jhajha", "Sikandra"],
      Jehanabad: ["Jehanabad", "Ghoshi", "Makhdumpur"],
      Kaimur: ["Bhabua", "Ramgarh", "Chenari"],
      Katihar: ["Katihar", "Barsoi", "Korha"],
      Khagaria: ["Khagaria", "Beldaur", "Parbatta"],
      Kishanganj: ["Kishanganj", "Bahadurganj", "Thakurganj"],
      Lakhisarai: ["Lakhisarai", "Halsi", "Chanan"],
      Madhepura: ["Madhepura", "Murliganj", "Bihariganj"],
      Madhubani: ["Madhubani", "Jhanjharpur", "Laukaha"],
      Munger: ["Munger", "HaveliKharagpur", "Tarapur"]
   },
  Karnataka: {
      Bagalkot: ["Bagalkot", "Jamkhandi", "Bilagi"],
    Ballari: ["Ballari", "Hospet", "Sandur"],
    Belagavi: ["Belagavi", "Chikkodi", "Bailhongal"],
    BengaluruRural: ["Devanahalli", "Doddaballapura", "Nelamangala"],
    BengaluruUrban: ["Bengaluru East", "Bengaluru West"],
    Bidar: ["Bidar", "Basavakalyan", "Humnabad"],
    Chamarajanagar: ["Chamarajanagar", "Gundlupet", "Yelandur"],
    Chikkaballapur: ["Chikkaballapur", "Gauribidanur", "Bagepalli"],
    Chikkamagaluru: ["Chikkamagaluru", "Koppa", "Mudigere"],
    Chitradurga: ["Chitradurga", "Challakere", "Hiriyur"],
    DakshinaKannada: ["Mangaluru", "Bantwal", "Puttur"],
    Davanagere: ["Davanagere", "Harihar"],
    Dharwad: ["Hubli", "Dharwad"],
    Gadag: ["Gadag", "Ron"],
    Hassan: ["Hassan", "Alur", "Arkalgud"],
    Haveri: ["Haveri", "Byadagi", "Hangal"],
    Kalaburagi: ["Kalaburagi", "Aland", "Afzalpur", "Chincholi"],
    Kodagu: ["Madikeri", "Virajpet", "Somwarpet"],
    Kolar: ["Kolar", "Bangarapet", "Malur", "Mulbagal"],
    Koppal: ["Koppal", "Gangawati", "Yelburga"],
    Mandya: ["Mandya", "Maddur", "Malavalli"],
    Mysuru: ["Mysuru", "Hunsur", "Nanjangud"],
    Raichur: ["Raichur", "Devadurga", "Sindhanur"],
    Ramanagara: ["Ramanagara", "Channarayapatna", "Kanakapura"],
    Shivamogga: ["Shivamogga", "Bhadravathi", "Sagar", "Sorab"],
    Tumakuru: ["Tumakuru", "Tiptur", "Madhugiri"],
    Udupi: ["Udupi", "Kundapura", "Karkala"],
    UttaraKannada: ["Karwar", "Sirsi", "Siddapur", "Honnavar"],
    Vijayapura: ["Vijayapura", "Indi", "Sindgi"],
    Yadgir: ["Yadgir", "Shahapur"]
  },
  
  Goa: {
      NorthGoa: ["Panaji", "Mapusa", "Bicholim"],
      SouthGoa: ["Margao", "Vasco", "Ponda"]
    },
    Gujarat: {
      Ahmedabad: ["Ahmedabad", "Gandhinagar", "Dholka"],
      Amreli: ["Amreli", "Dhari", "Savarkundla"],
      Anand: ["Anand", "Khambhat", "Petlad"],
      Aravalli: ["Modasa", "Malpur", "Dhansura"],
      Banaskantha: ["Palanpur", "Deesa", "Dhanera"],
      Bharuch: ["Bharuch", "Ankleshwar", "Jambusar"],
      Bhavnagar: ["Bhavnagar", "Talaja", "Mahuva"],
      Botad: ["Botad", "Gadhada", "Barwala"],
      ChhotaUdaipur: ["ChhotaUdaipur", "Sankheda", "JetpurPavi"],
      Dahod: ["Dahod", "Limbdi", "Dhanpur"],
      Dang: ["Ahwa", "Saputara", "Subir"],
      DevbhoomiDwarka: ["Khambhalia", "Okha", "Kalyanpur"],
      Gandhinagar: ["Gandhinagar", "Kalol", "Dehgam"],
      GirSomnath: ["Veraval", "Una", "Talala"],
      Jamnagar: ["Jamnagar", "Dwarka", "Jodiya"],
      Junagadh: ["Junagadh", "Mangrol", "Visavadar"],
      Kheda: ["Nadiad", "Mehmedabad", "Kapadvanj"],
      Kutch: ["Bhuj", "Mandvi", "Anjar"],
      Mahisagar: ["Lunawada", "Godhra", "Santrampur"],
      Mehsana: ["Mehsana", "Visnagar", "Vijapur"],
      Morbi: ["Morbi", "Wankaner", "Tankara"],
      Narmada: ["Rajpipla", "Dediapada", "Nandod"],
      Navsari: ["Navsari", "Gandevi", "Bilimora"],
      Panchmahal: ["Godhra", "Halol", "Kalol"],
      Patan: ["Patan", "Sidhpur", "Radhanpur"],
      Porbandar: ["Porbandar", "Kutiyana", "Ranavav"],
      Rajkot: ["Rajkot", "Jetpur", "Morbi"],
      Sabarkantha: ["Himmatnagar", "Idar", "Prantij"],
      Surat: ["Surat", "Bardoli", "Navsari"],
      Surendranagar: ["Surendranagar", "Wadhwan", "Dhrangadhra"],
      Tapi: ["Vyara", "Songadh", "Uchchhal"],
      Vadodara: ["Vadodara", "Padra", "Karjan"],
      Valsad: ["Valsad", "Vapi", "Dharampur"]
    },
    Haryana: {
      Ambala: ["Ambala", "Naraingarh", "Barara"],
      Bhiwani: ["Bhiwani", "Loharu", "Siwani"],
      CharkhiDadri: ["CharkhiDadri", "Badhra", "Bayal"],
      Faridabad: ["Faridabad", "Ballabhgarh", "Palwal"],
      Fatehabad: ["Fatehabad", "Tohana", "Ratia"],
      Gurugram: ["Gurugram", "Sohna", "Pataudi"],
      Hisar: ["Hisar", "Adampur", "Uklanamandi"],
      Jhajjar: ["Jhajjar", "Bahadurgarh", "Matenhail"],
      Jind: ["Jind", "Safidon", "Uchana"],
      Kaithal: ["Kaithal", "Pundri", "Kalayat"],
      Karnal: ["Karnal", "Assandh", "Gharaunda"],
      Kurukshetra: ["Kurukshetra", "Thanesar", "Pehowa"],
      Mahendragarh: ["Narnaul", "Mahendragarh", "Ateli"],
      Nuh: ["Nuh", "FerozepurJhirka", "Taoru"],
      Palwal: ["Palwal", "Hodal", "Hassanpur"],
      Panchkula: ["Panchkula", "Kalka", "Pinjore"],
      Panipat: ["Panipat", "Samalkha", "Israna"],
      Rewari: ["Rewari", "Bawal", "Kosli"],
      Rohtak: ["Rohtak", "Maham", "Kalanaur"],
      Sirsa: ["Sirsa", "Dabwali", "Ellenabad"],
      Sonipat: ["Sonipat", "Gohana", "Kharkhoda"],
      Yamunanagar: ["Yamunanagar", "Jagadhri", "Chhachhrauli"]
    },
    HimachalPradesh: {
      Bilaspur: ["Bilaspur", "Ghumarwin", "Jhandutta"],
      Chamba: ["Chamba", "Dalhousie", "Bharmour"],
      Hamirpur: ["Hamirpur", "Barsar", "Nadaun"],
      Kangra: ["Dharamshala", "Kangra", "Palampur"],
      Kinnaur: ["ReckongPeo", "Kalpa", "Nichar"],
      Kullu: ["Kullu", "Banjar", "Manali"],
      LahaulandSpiti: ["Keylong", "Lahaul", "Spiti"],
      Mandi: ["Mandi", "Sundernagar", "Jogindernagar"],
      Shimla: ["Shimla", "Rampur", "Theog"],
      Sirmaur: ["Nahan", "PaontaSahib", "Rajgarh"],
      Solan: ["Solan", "Nalagarh", "Arki"],
      Una: ["Una", "Bangana", "Amb"]
    },
    Jharkhand: {
      Bokaro: ["Bokaro", "Chandankiyari", "Kasmar"],
      Chatra: ["Chatra", "Simaria", "Tandwa"],
      Deoghar: ["Deoghar", "Sarwan", "Madhupur"],
  Dhanbad: ["Dhanbad", "Baghmara", "Tundi"],
      Dumka: ["Dumka", "Jama", "Masalia"],
      EastSinghbhum: ["Jamshedpur", "Ghatshila", "Baharagora"],
      Garhwa: ["Garhwa", "Bhandaria", "Ramkanda"],
      Giridih: ["Giridih", "Dhanwar", "Tisri"],
      Godda: ["Godda", "Boarijore", "Mahagama"],
      Gumla: ["Gumla", "Chainpur", "Ghaghra"],
      Hazaribagh: ["Hazaribagh", "Barkagaon", "Ichak"],
      Jamtara: ["Jamtara", "Fatehpur", "Karmatanr"],
      Khunti: ["Khunti", "Torpa", "Karra"],
      Koderma: ["Koderma", "Domchanch", "Chandwara"],
      Latehar: ["Latehar", "Balumath", "Manika"],
      Lohardaga: ["Lohardaga", "Kuru", "Bhandra"],
      Pakur: ["Pakur", "Amrapara", "Maheshpur"],
      Palamu: ["Daltonganj", "Lesliganj", "Pandu"],
      Ramgarh: ["Ramgarh", "Patratu", "Gola"],
      Ranchi: ["Ranchi", "Kanke", "Angara"],
      Sahebganj: ["Sahebganj", "Borio", "Barhait"],
      SaraikelaKharsawan: ["Saraikela", "Kharsawan", "Rajnagar"],
      Simdega: ["Simdega", "Kolebira", "Bolba"],
      WestSinghbhum: ["Chaibasa", "Chakradharpur", "Noamundi"]
    },
   Kerala: {
      Alappuzha: ["Alappuzha", "Chengannur", "Mavelikkara"],
      Ernakulam: ["Kochi", "Kothamangalam", "Aluva"],
      Idukki: ["Idukki", "Thodupuzha", "Devikulam"],
      Kannur: ["Kannur", "Thalassery", "Iritty"],
      Kasaragod: ["Kasaragod", "Kanhangad", "Nileshwar"],
      Kollam: ["Kollam", "Karunagappally", "Punalur"],
      Kottayam: ["Kottayam", "Changanassery", "Vaikom"],
      Kozhikode: ["Kozhikode", "Vadakara", "Thamarassery"],
      Malappuram: ["Malappuram", "Manjeri", "Perinthalmanna"],
      Palakkad: ["Palakkad", "Ottappalam", "Pattambi"],
      Pathanamthitta: ["Pathanamthitta", "Tiruvalla", "Adoor"],
      Thiruvananthapuram: ["Thiruvananthapuram", "Neyyattinkara", "Attingal"],
      Thrissur: ["Thrissur", "Chalakudy", "Kunnamkulam"],
      Wayanad: ["Kalpetta", "Mananthavady", "Sulthan Bathery"]
    },
    MadhyaPradesh: {
      AgarMalwa: ["Agar", "Badod", "Susner"],
      Alirajpur: ["Alirajpur", "Bhavra", "Jobat"],
      Anuppur: ["Anuppur", "Kotma", "Pushprajgarh"],
      Ashoknagar: ["Ashoknagar", "Chanderi", "Isagarh"],
      Balaghat: ["Balaghat", "Katangi", "Lanji"],
      Barwani: ["Barwani", "Anjad", "Sendhwa"],
      Betul: ["Betul", "Amla", "Multai"],
      Bhind: ["Bhind", "Ater", "Gohad"],
      Bhopal: ["Bhopal", "Berasia", "Huzur"],
      Burhanpur: ["Burhanpur", "Khaknar", "Nepanagar"],
      Chhatarpur: ["Chhatarpur", "Bada Malhera", "Bijawar"],
      Chhindwara: ["Chhindwara", "Amlai", "Pandhurna"],
      Damoh: ["Damoh", "Hatta", "Tendukheda"],
      Datia: ["Datia", "Bhander", "Seondha"],
      Dewas: ["Dewas", "Bagli", "Kannod"],
      Dhar: ["Dhar", "Badnawar", "Kukshi"],
      Dindori: ["Dindori", "Shahpura", "Niwas"],
      Guna: ["Guna", "Aron", "Raghogarh"],
      Gwalior: ["Gwalior", "Dabra", "Bhitarwar"],
      Harda: ["Harda", "Handia", "Khirkiya"],
      Hoshangabad: ["Hoshangabad", "Babai", "Itarsi"],
      Indore: ["Indore", "Depalpur", "Sanwer"],
      Jabalpur: ["Jabalpur", "Kundam", "Panagar"],
      Jhabua: ["Jhabua", "Petlawad", "Thandla"],
      Katni: ["Katni", "Badwara", "Vijayraghavgarh"],
      Khandwa: ["Khandwa", "Pandhana", "Punasa"],
      Khargone: ["Khargone", "Barwah", "Bhikangaon"],
      Mandla: ["Mandla", "Bamhani", "Dindori"],
      Mandsaur: ["Mandsaur", "Daloda", "Garoth"],
      Morena: ["Morena", "Ambah", "Joura"],
      Narsinghpur: ["Narsinghpur", "Gadarwara", "Gotegaon"],
      Neemuch: ["Neemuch", "Jawad", "Manasa"],
      Panna: ["Panna", "Ajaigarh", "Gunnor"],
      Raisen: ["Raisen", "Begamganj", "Goharganj"],
      Rajgarh: ["Rajgarh", "Khilchipur", "Narsinghgarh"],
      Ratlam: ["Ratlam", "Alot", "Sailana"],
      Rewa: ["Rewa", "Huzur", "Govindgarh"],
      Sagar: ["Sagar", "Bina", "Rahatgarh"],
      Satna: ["Satna", "Maihar", "Nagod"],
      Sehore: ["Sehore", "Ashta", "Ichhawar"],
      Seoni: ["Seoni", "Barghat", "Chhapara"],
      Shahdol: ["Shahdol", "Anuppur", "Beohari"],
      Shajapur: ["Shajapur", "Agar", "Badodiya"],
      Sheopur: ["Sheopur", "Badoda", "Vijaypur"],
      Shivpuri: ["Shivpuri", "Kolaras", "Pichhore"],
      Sidhi: ["Sidhi", "Churhat", "Gopadbanas"],
      Singrauli: ["Singrauli", "Chitrangi", "Deosar"],
      Tikamgarh: ["Tikamgarh", "Baldeogarh", "Jatara"],
      Ujjain: ["Ujjain", "Badnagar", "Mahidpur"],
      Umaria: ["Umaria", "Bandhogarh", "Manpur"],
      Vidisha: ["Vidisha", "Basoda", "Kurwai"]
    },
    Maharashtra: {
      Ahmednagar: ["Ahmednagar", "Shrirampur", "Rahuri"],
      Akola: ["Akola", "Akot", "Balapur"],
      Amravati: ["Amravati", "Daryapur", "Chandurbazar"],
      Aurangabad: ["Aurangabad", "Gangapur", "Paithan"],
      Beed: ["Beed", "Georai", "Ashti"],
   Bhandara: ["Bhandara", "Sakoli", "Lakhandur"],
      Buldhana: ["Buldhana", "Chikhli", "Malkapur"],
      Chandrapur: ["Chandrapur", "Ballarpur", "Brahmapuri"],
      Dhule: ["Dhule", "Sakri", "Shirpur"],
      Gadchiroli: ["Gadchiroli", "Chamorshi", "Armori"],
      Gondia: ["Gondia", "Tiroda", "Goregaon"],
      Hingoli: ["Hingoli", "Basmath", "Aundha"],
      Jalgaon: ["Jalgaon", "Bhusawal", "Yawal"],
      Jalna: ["Jalna", "Bhokardan", "Ambad"],
      Kolhapur: ["Kolhapur", "Karvir", "Gadhinglaj"],
      Latur: ["Latur", "Ahmadpur", "Udgir"],
      MumbaiCity: ["Mumbai", "Ward", "Byculla"],
      MumbaiSuburban: ["Andheri", "Borivali", "Kandivali"],
      Nagpur: ["Nagpur", "Kamptee", "Hingna"],
      Nanded: ["Nanded", "Bhokar", "Ardhapur"],
      Nandurbar: ["Nandurbar", "Shahada", "Akkalkuwa"],
      Nashik: ["Nashik", "Malegaon", "Sinnar"],
      Osmanabad: ["Osmanabad", "Paranda", "Tuljapur"],
      Palghar: ["Palghar", "Vasai", "Wada"],
      Parbhani: ["Parbhani", "Gangakhed", "Jintur"],
      Pune: ["Pune", "PimpriChinchwad", "Baramati"],
      Raigad: ["Alibag", "Panvel", "Mahad"],
      Ratnagiri: ["Ratnagiri", "Chiplun", "Guhagar"],
      Sangli: ["Sangli", "Miraj", "Islampur"],
      Satara: ["Satara", "Karad", "Wai"],
      Sindhudurg: ["Sindhudurg", "Kudal", "Vengurla"],
      Solapur: ["Solapur", "Akkalkot", "Pandharpur"],
      Thane: ["Thane", "Kalyan", "Ulhasnagar"],
      Wardha: ["Wardha", "Deoli", "Hinganghat"],
      Washim: ["Washim", "Risod", "Mangrulpir"],
      Yavatmal: ["Yavatmal", "Wani", "Pusad"]
    },
    Manipur: {
      Bishnupur: ["Bishnupur", "Moirang", "Nambol"],
      Chandel: ["Chandel", "Chakpikarong", "Machi"],
      Churachandpur: ["Churachandpur", "Singngat", "Samulamlan"],
      ImphalEast: ["Imphal", "Jiribam", "Lamlai"],
      ImphalWest: ["Lamphelpat", "Patsoi", "Sekmai"],
      Senapati: ["Senapati", "Kangpokpi", "Mao"],
      Tamenglong: ["Tamenglong", "Tamei", "Nungba"],
      Thoubal: ["Thoubal", "Kakching", "Lilong"],
      Ukhrul: ["Ukhrul", "Kamjong", "KasomKhullen"]
    },
    Meghalaya: {
      EastGaroHills: ["Williamnagar", "Baghmara", "Resubelpara"],
      EastJaintiaHills: ["Khliehriat", "Amlarem", "Jowai"],
      EastKhasiHills: ["Shillong", "Mawkynrew", "Nongpoh"],
      NorthGaroHills: ["Resubelpara", "Dainadubi", "Kharkutta"],
      RiBhoi: ["Nongpoh", "Umling", "Jirang"],
      SouthGaroHills: ["Baghmara", "Gasuapara", "Rongara"],
      SouthWestGarohills: ["Ampati", "Betasing", "Zikzak"],
      WestGaroHills: ["Tura", "Dadenggre", "Raksamgre"],
      WestJaintiaHills: ["Jowai", "Amlarem", "Ladrymbai"],
      WestKhasiHills: ["Nongstoin", "Mawshynrut", "Mawthadraishan"]
    },
    Mizoram: {
      Aizawl: ["Aizawl", "Darlawn", "Tlangnuam"],
      Champhai: ["Champhai", "Khawbung", "Ngopa"],
      Hnahthial: ["Hnahthial", "Tawipui", "Sangau"],
      Khawzawl: ["Khawzawl", "Khawbung", "Ngopa"],
      Kolasib: ["Kolasib", "Bilkhawthlir", "Thingdawl"],
      Lawngtlai: ["Lawngtlai", "Chawngte", "Vaseikai"],
      Lunglei: ["Lunglei", "Tlabung", "Bunghmun"],
      Mamit: ["Mamit", "Kawrthah", "Zawlnuam"],
      Saiha: ["Saiha", "Tuipang", "Sangua"],
      Serchhip: ["Serchhip", "Senvon", "Bukpui"]
    },
    Nagaland: {
      Dimapur: ["Dimapur", "Kohima", "Mokokchung"],
      Kiphire: ["Kiphire", "Longmatra", "Seyochung"],
      Kohima: ["Kohima", "Chiephobozou", "Jakhama"],
      Longleng: ["Longleng", "Sangtam", "Tamlu"],
      Mokokchung: ["Mokokchung", "Changtongya", "Tuli"],
      Mon: ["Mon", "Aboi", "Naginimora"],
      Peren: ["Peren", "Ahthibung", "Tening"],
      Phek: ["Phek", "Chozuba", "Kikruma"],
      Tuensang: ["Tuensang", "Changtongya", "Noksen"],
      Wokha: ["Wokha", "Bhandari", "Sanis"],
      Zunheboto: ["Zunheboto", "Aghunato", "Satakha"]
    },
    Odisha: {
      Angul: ["Angul", "Athmallik", "Pallahara"],
      Balangir: ["Balangir", "Balakot", "Deogaon"],
      Balasore: ["Balasore", "Basta", "Bhadrak"],
      Bargarh: ["Bargarh", "Padampur", "Bhatli"],
      Bhadrak: ["Bhadrak", "Bhandaripokhari", "Tihidi"],
      Cuttack: ["Cuttack", "Athagarh", "Badamba"],
      Deogarh: ["Deogarh", "Barkote", "Reamal"],
      Dhenkanal: ["Dhenkanal", "Bhuban", "Kamakhyanagar"],
      Gajapati: ["Parlakhemundi", "Mohana", "Kashinagar"],
      Ganjam: ["Berhampur", "Chhatrapur", "Bhanjanagar"],
      Jagatsinghpur: ["Jagatsinghpur", "Paradip", "Raghunathpur"],
      Jajpur: ["Jajpur", "JajpurRoad", "Kuakhia"],
      Jharsuguda: ["Jharsuguda", "Kolabira", "Laikera"],
      Kalahandi: ["Bhawanipatna", "Dharamgarh", "Junagarh"],
      Kandhamal: ["Phulbani", "Baliguda", "Daringbadi"],
      Kendrapara: ["Kendrapara", "Kendrapara", "Pattamundai"],
      Kendujhar: ["Kendujhar", "Anandapur", "Champua"],
      Khordha: ["Bhubaneswar", "Jatni", "Khordha"],
      Koraput: ["Koraput", "Jeypore", "Sunabeda"],
      Malkangiri: ["Malkangiri", "Malkangiri", "Malkangiri"],
      Mayurbhanj: ["Baripada", "Rairangpur", "Karanjia"],
      Nabarangpur: ["Nabarangpur", "Umarkote", "Dabugam"],
      Nayagarh: ["Nayagarh", "Khandapara", "Odagaon"],
      Nuapada: ["Nuapada", "Boden", "Khariar"],
      Puri: ["Puri", "Konark", "Nimapara"],
      Rayagada: ["Rayagada", "Gunupur", "Gudari"],
      Sambalpur: ["Sambalpur", "Burla", "Jujumura"],
      Subarnapur: ["Subarnapur", "Birmaharajpur", "Dunguripali"],
      Sundargarh: ["Sundargarh", "Biramitrapur", "Rajgangpur"]
    },
    Punjab: {
      Amritsar: ["Amritsar", "Ajnala", "TarnTaran"],
      Barnala: ["Barnala", "Barnala", "Tapa"],
      Bathinda: ["Bathinda", "Bathinda", "RampuraPhul"],
      Faridkot: ["Faridkot", "Faridkot", "Kotkapura"],
      FatehgarhSahib: ["FatehgarhSahib", "Amloh", "BassiPathana"],
      Fazilka: ["Fazilka", "Fazilka", "Jalalabad"],
      Ferozepur: ["Ferozepur", "Ferozepur", "Zira"],
      Gurdaspur: ["Gurdaspur", "Batala", "DeraBabaNanak"],
      Hoshiarpur: ["Hoshiarpur", "Hoshiarpur", "Garhdiwala"],
      Jalandhar: ["Jalandhar", "Nakodar", "Phillaur"],
      Kapurthala: ["Kapurthala", "Kapurthala", "Sultanpur"],
      Ludhiana: ["Ludhiana", "Jagraon", "Khanna"],
      Mansa: ["Mansa", "Mansa", "Budhlada"],
      Moga: ["Moga", "Moga", "Nihal Singh Wala"],
      Muktsar: ["Muktsar", "Malout", "Gidderbaha"],
      Pathankot: ["Pathankot", "Pathankot", "Pathankot"],
      Patiala: ["Patiala", "Nabha", "Rajpura"],
      Rupnagar: ["Rupnagar", "Rupnagar", "Anandpur Sahib"]
  },
  Sikkim: {
      EastSikkim: ["Gangtok", "Rangpo", "Singtam"],
      NorthSikkim: ["Chungthang", "Mangan", "Dzongu"],
      SouthSikkim: ["Namchi", "Jorethang", "Ravongla"],
      WestSikkim: ["Geyzing", "Yuksom", "Soreng"]
    },
    TamilNadu: {
      Ariyalur: ["Ariyalur", "Udayarpalayam", "Sendurai"],
      Chengalpattu: ["Chengalpattu", "Tambaram", "ChengalpattuTaluk"],
      Chennai: ["Chennai", "Alandur", "Adyar"],
      Coimbatore: ["Coimbatore", "Pollachi", "Mettupalayam"],
      Cuddalore: ["Cuddalore", "Chidambaram", "Virudhachalam"],
      Dharmapuri: ["Dharmapuri", "Harur", "Palakkodu"],
      Dindigul: ["Dindigul", "Palani", "Natham"],
      Erode: ["Erode", "Gobichettipalayam", "Sathyamangalam"],
      Kallakurichi: ["Kallakurichi", "Chinnasalem", "Ulundurpet"],
      Kanchipuram: ["Kanchipuram", "Chengalpattu", "Sriperumbudur"],
      Kanyakumari: ["Nagercoil", "Padmanabhapuram", "Kuzhithurai"],
      Karur: ["Karur", "Aravakurichi", "Kadavur"],
      Krishnagiri: ["Krishnagiri", "Hosur", "Uthangarai"],
      Madurai: ["Madurai", "Melur", "Usilampatti"],
      Nagapattinam: ["Nagapattinam", "Mayiladuthurai", "Sirkazhi"],
      Namakkal: ["Namakkal", "Paramathi", "Rasipuram"],
      Nilgiris: ["Udhagamandalam", "Coonoor", "Kotagiri"],
      Perambalur: ["Perambalur", "Kunnam", "Veppanthattai"],
      Pudukkottai: ["Pudukkottai", "Aranthangi", "Illupur"],
      Ramanathapuram: ["Ramanathapuram", "Mudukulathur", "Paramakudi"],
      Ranipet: ["Ranipet", "Arcot", "Arakonam"],
      Salem: ["Salem", "Attur", "Edappadi"],
      Sivaganga: ["Sivaganga", "Manamadurai", "Thirupathur"],
      Tenkasi: ["Tenkasi", "Shenkottai", "Sivagiri"],
      Thanjavur: ["Thanjavur", "Kumbakonam", "Pattukkottai"],
      Theni: ["Theni", "Periyakulam", "Bodinayakanur"],
      Thoothukudi: ["Thoothukudi", "Kovilpatti", "Ottapidaram"],
      Tiruchirappalli: ["Tiruchirappalli", "Lalgudi", "Musiri"],
      Tirunelveli: ["Tirunelveli", "Ambasamudram", "Palayamkottai"],
      Tirupathur: ["Tirupathur", "Vaniyambadi", "Ambur"],
      Tiruppur: ["Tiruppur", "Avanashi", "Palladam"],
      Tiruvallur: ["Tiruvallur", "Ponneri", "Gummidipoondi"],
      Tiruvannamalai: ["Tiruvannamalai", "Arni", "Chengam"],
      Tiruvarur: ["Tiruvarur", "Mannargudi", "Nannilam"],
      Vellore: ["Vellore", "Arakkonam", "Vaniyambadi"],
      Viluppuram: ["Viluppuram", "Kallakurichi", "Tindivanam"],
      Virudhunagar: ["Virudhunagar", "Aruppukkottai", "Sivakasi"]
    },
    Telangana: {
      Adilabad: ["Adilabad", "Bhainsa", "Nirmal"],
      BhadradriKothagudem: ["Kothagudem", "Bhadradri", "Palvancha"],
      Hyderabad: ["Hyderabad", "Secunderabad", "Quthbullapur"],
      Jagtial: ["Jagtial", "Metpalle", "Koratla"],
      Jangaon: ["Jangaon", "Ghanpur", "Cherial"],
      JayashankarBhupalpally: ["Bhupalpally", "Thorrur", "Venkatapur"],
      JogulambaGadwal: ["Gadwal", "Alampur", "Wanaparthy"],
      Kamareddy: ["Kamareddy", "Banswada", "Yellareddy"],
      Karimnagar: ["Karimnagar", "Jagtial", "Koratla"],
      Khammam: ["Khammam", "Kothagudem", "Madhira"],
      KumuramBheemAsifabad: ["Asifabad", "Kerameri", "Kotapalle"],
      Mahabubabad: ["Mahabubabad", "Thorrur", "Maripeda"],
      Mahabubnagar: ["Mahabubnagar", "Achampet", "Narayanpet"],
      Mancherial: ["Mancherial", "Kyathanpalle", "Naspur"],
      Medak: ["Medak", "Siddipet", "Narsapur"],
      MedchalMalkajgiri: ["Medchal", "Ghatkesar", "Alwal"],
      Nagarkurnool: ["Nagarkurnool", "Achampet", "Kalwakurthy"],
   Nalgonda: ["Nalgonda", "Bhongir", "Suryapet"],
      Nirmal: ["Nirmal", "Bhainsa", "Khanapur"],
      Nizamabad: ["Nizamabad", "Armoor", "Bodhan"],
      Peddapalli: ["Peddapalli", "Ramagundam", "Sircilla"],
      RajannaSircilla: ["Sircilla", "Vemulawada", "Jagityal"],
      Rangareddy: ["L.B. Nagar", "Malkajgiri", "Quthbullapur"],
      Sangareddy: ["Sangareddy", "Zaheerabad", "Andole"],
      Siddipet: ["Siddipet", "Gajwel", "Husnabad"],
      Suryapet: ["Suryapet", "Thungathurthy", "Nakrekal"],
      Vikarabad: ["Vikarabad", "Tandur", "Pargi"],
      Wanaparthy: ["Wanaparthy", "Kothakota", "Atmakur"],
      WarangalRural: ["Warangal", "Parakala", "Narsampet"],
      WarangalUrban: ["Warangal", "Hanamkonda", "Kazipet"],
      YadadriBhuvanagiri: ["Bhuvanagiri", "Alair", "Jangaon"]
    },
    Tripura: {
      Dhalai: ["Ambassa", "Dharamnagar", "Kumarghat"],
      Gomati: ["Udaipur", "Bokafa", "Killa"],
      Khowai: ["Khowai", "Teliamura", "Kamalpur"],
      NorthTripura: ["Dharmanagar", "Kanchanpur", "Panisagar"],
      Sepahijala: ["Bishalgarh", "Sonamura", "Jirania"],
      SouthTripura: ["Belonia", "Sabroom", "Amarpur"],
      Unakoti: ["Kailashahar", "Kumarghat", "Santirbazar"],
      WestTripura: ["Agartala", "Dukli", "Jirania"]
    },
    UttarPradesh: {
      Agra: ["Agra", "FatehpurSikri", "Kiraoli"],
      Aligarh: ["Aligarh", "Khair", "Iglas"],
      AmbedkarNagar: ["Akbarpur", "Tanda", "Jalalpur"],
      Amethi: ["Gauriganj", "Musafirkhana", "Tiloi"],
      Amroha: ["Amroha", "Dhanaura", "Hasanpur"],
      Auraiya: ["Bidhuna", "Auraiya", "Sikandra"],
      Ayodhya: ["Faizabad", "Tanda", "Bikapur"],
      Azamgarh: ["Azamgarh", "Lalganj", "Mau"],
      Baghpat: ["Baghpat", "Baraut", "Khekra"],
      Bahraich: ["Bahraich", "Nanpara", "Kaiserganj"],
      Ballia: ["Ballia", "Rasra", "Bairia"],
      Balrampur: ["Balrampur", "Tulsipur", "Utraula"],
      Banda: ["Banda", "Atarra", "Naraini"],
      Barabanki: ["Barabanki", "Fatehpur", "Haidergarh"],
      Bareilly: ["Bareilly", "Aonla", "Nawabganj"],
      Basti: ["Basti", "Haraiya", "Bhanpur"],
      Bhadohi: ["Bhadohi", "Gyanpur", "Aurai"],
      Bijnor: ["Bijnor", "Chandpur", "Najibabad"],
      Bulandshahr: ["Bulandshahr", "Sikandrabad", "Khurja"],
      Chandauli: ["Chandauli", "Sakaldiha", "Mughalsarai"],
      Chitrakoot: ["Chitrakoot", "Karwi", "Manikpur"],
      Deoria: ["Deoria", "Barhaj", "BhatparRani"],
      Etah: ["Etah", "Aliganj", "Jalesar"],
      Etawah: ["Etawah", "Auraiya", "Bharthana"],
      Faizabad: ["Faizabad", "Tanda", "Bikapur"],
      Farrukhabad: ["Farrukhabad", "Kaimganj", "Kamalganj"],
      Fatehpur: ["Fatehpur", "Bindki", "Khaga"],
      Firozabad: ["Firozabad", "Shikohabad", "Tundla"],
      GautamBuddhaNagar: ["Noida", "GreaterNoida", "Dadri"],
      Ghaziabad: ["Ghaziabad", "Modinagar", "Loni"],
      Ghazipur: ["Ghazipur", "Jangipur", "Saidpur"],
      Gonda: ["Gonda", "Colonelganj", "Mankapur"],
      Gorakhpur: ["Gorakhpur", "Sahjanwa", "Bansgaon"],
      Hamirpur: ["Hamirpur", "Maudaha", "Rath"],
      Hapur: ["Hapur", "Dhaulana", "Pilkhuwa"],
      Hardoi: ["Hardoi", "Bilgram", "Sandila"],
      Hathras: ["Hathras", "SikandraRao", "Sasni"],
      Jalaun: ["Orai", "Kalpi", "Konch"],
      Jaunpur: ["Jaunpur", "Shahganj", "Machhlishahr"],
      Jhansi: ["Jhansi", "Mauranipur", "Garautha"],
      Kannauj: ["Kannauj", "Chhibramau", "Tirwa"],
      KanpurDehat: ["Rasulabad", "Akbarpur", "Rura"],
      KanpurNagar: ["Kanpur", "Bilhaur", "Sikandra"],
      Kasganj: ["Kasganj", "Patiyali", "Soron"],
      Kaushambi: ["Manjhanpur", "Sirathu", "Chail"],
      Kushinagar: ["Padrauna", "Hata", "Kaptanganj"],
      LakhimpurKheri: ["Lakhimpur", "Nighasan", "GolaGokaranNath"],
      Lalitpur: ["Lalitpur", "Mahroni", "Talbehat"],
   Lucknow: ["Aliganj", "Gomti Nagar", "Indira Nagar"],
      Maharajganj: ["Maharajganj", "Nautanwa", "Pharenda"],
      Mahoba: ["Mahoba", "Charkhari", "Kulpahar"],
      Mainpuri: ["Mainpuri", "Karhal", "Kishni"],
      Mathura: ["Mathura", "Vrindavan", "Govardhan"],
      Mau: ["Mau", "Muhammadabad", "Ghosi"],
      Meerut: ["Meerut", "Sardhana", "Mawana"],
      Mirzapur: ["Mirzapur", "Chunar", "Robertsganj"],
      Moradabad: ["Moradabad", "Sambhal", "Kanth"],
      Muzaffarnagar: ["Muzaffarnagar", "Khatauli", "Jansath"],
      Pilibhit: ["Pilibhit", "Bisalpur", "Puranpur"],
      Pratapgarh: ["Pratapgarh", "Kunda", "Raniganj"],
      RaeBareli: ["RaeBareli", "Lalganj", "Unchahar"],
      Rampur: ["Rampur", "Bilaspur", "Milak"],
      Saharanpur: ["Saharanpur", "Behat", "Nakur"],
      Sambhal: ["Sambhal", "Gunnaur", "Chandausi"],
      SantKabirNagar: ["Khalilabad", "Mehnagar", "Dhanghata"],
      Shahjahanpur: ["Shahjahanpur", "Powayan", "Tilhar"],
      Shamli: ["Shamli", "Kairana", "Un"]
    },
    Uttarakhand: {
      Almora: ["Almora", "Dwarahat", "Ranikhet"],
      Bageshwar: ["Bageshwar", "Kapkot", "Garur"],
      Chamoli: ["Gopeshwar", "Joshimath", "Tharali"],
      Champawat: ["Champawat", "Lohaghat", "Tanakpur"],
      Dehradun: ["Dehradun", "Chakrata", "Rishikesh"],
      Haridwar: ["Haridwar", "Roorkee", "Najibabad"],
      Nainital: ["Nainital", "Haldwani", "Ramnagar"],
      PauriGarhwal: ["Pauri", "Lansdowne", "Srinagar"],
      Pithoragarh: ["Pithoragarh", "Didihat", "Gangolihat"],
      Rudraprayag: ["Rudraprayag", "Kedarnath", "Augustmuni"],
      TehriGarhwal: ["New Tehri", "Barkot", "Dhanaulti"],
      UdhamSinghNagar: ["Rudrapur", "Kichha", "Bajpur"],
      Uttarkashi: ["Uttarkashi", "Bhatwari", "Naugaon"]
    },
    WestBengal: {
      Alipurduar: ["Alipurduar", "Falakata", "Jaigaon"],
      Bankura: ["Bankura", "Bishnupur", "Khatra"],
      Birbhum: ["Suri", "Bolpur", "Rampurhat"],
      CoochBehar: ["CoochBehar", "Dinhata", "Mathabhanga"],
      DakshinDinajpur: ["Balurghat", "Gangarampur", "Tapan"],
      Darjeeling: ["Darjeeling", "Kalimpong", "Kurseong"],
      Hooghly: ["Chinsurah", "Serampore", "Arambagh"],
      Howrah: ["Howrah", "Bally", "Uluberia"],
      Jalpaiguri: ["Jalpaiguri", "Dhupguri", "Mal"],
      Jhargram: ["Jhargram", "Gopiballavpur", "Binpur"],
      Kalimpong: ["Kalimpong", "Kalimpong", "Kalimpong"],
      Kolkata: ["Kolkata", "Kolkata", "Kolkata"],
      Malda: ["English Bazar", "Old Malda", "Chanchal"],
      Murshidabad: ["Baharampur", "Jangipur", "Lalgola"],
      Nadia: ["Krishnanagar", "Nabadwip", "Ranaghat"],
      North24Parganas: ["Barasat", "Basirhat", "Bidhannagar"],
      PaschimBardhaman: ["Asansol", "Durgapur", "Raniganj"],
      PaschimMedinipur: ["Midnapore", "Kharagpur", "Haldia"],
      PurbaBardhaman: ["Burdwan", "Asansol", "Durgapur"],
      PurbaMedinipur: ["Tamluk", "Haldia", "Contai"],
      Purulia: ["Purulia", "Raghunathpur", "Jhalda"],
      South24Parganas: ["Alipore", "Baruipur", "DiamondHarbour"],
      UttarDinajpur: ["Raiganj", "Kaliaganj", "Islampur"]
  },
  
  } ;



export {talukData };
  